// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNh4jjATuFZN7v4axEJ8FwVPmydtq95uc',
    appId: '1:767992730755:web:fa6e56cafc8bf490cff7b6',
    messagingSenderId: '767992730755',
    projectId: 'vital-flex',
    authDomain: 'vital-flex.firebaseapp.com',
    storageBucket: 'vital-flex.firebasestorage.app',
    measurementId: 'G-0ZMZPW426S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_HOSEI8-Y9RGjJPFMXOc2p69NdaIs6Q4',
    appId: '1:767992730755:android:35ab32d78c65a4cfcff7b6',
    messagingSenderId: '767992730755',
    projectId: 'vital-flex',
    storageBucket: 'vital-flex.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4J0mVZ6UOsGI9hh4A8IJLullAHwuSXoQ',
    appId: '1:767992730755:ios:f5b8a375ae793780cff7b6',
    messagingSenderId: '767992730755',
    projectId: 'vital-flex',
    storageBucket: 'vital-flex.firebasestorage.app',
    iosBundleId: 'com.example.vitalFlex',
  );
}
